import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import NavBar_3 from "./components/navbar_3";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        {/* Satoshi font ka link */}
        <link
          href="https://fonts.googleapis.com/css2?family=Satoshi:wght@100;200;300;400;500;600;700&display=swap"
          rel="stylesheet"
        />
      </head>
      <body className={inter.className}>
        <NavBar_3 />
        {children}
      </body>
    </html>
  );
}
